import { Trade } from './types';
import { subDays, format, startOfDay } from 'date-fns';

export const MOCK_TRADES: Trade[] = [
  {
    id: '1',
    asset: 'BTC/USDT',
    marketType: 'Crypto',
    entryPrice: 62000,
    exitPrice: 65000,
    positionSize: 0.1,
    side: 'Long',
    entryDate: subDays(new Date(), 5).toISOString(),
    exitDate: subDays(new Date(), 5).toISOString(),
    strategy: 'Trend Continuation',
    notes: 'Strong bounce off 200 EMA on 4H chart.',
    emotionalState: 'Calm',
    confidence: 8,
    newsImpact: 'None',
    followedRules: ['Structure Break', 'Low Risk'],
    mistakeTags: [],
    pnl: 300,
    pnlPercentage: 4.8,
    riskReward: 2.5,
    targetRR: 3.0,
    exitStatus: 'Closed by T/P',
  },
  {
    id: '2',
    asset: 'EUR/USD',
    marketType: 'Forex',
    entryPrice: 1.0850,
    exitPrice: 1.0820,
    positionSize: 100000,
    side: 'Short',
    entryDate: subDays(new Date(), 4).toISOString(),
    exitDate: subDays(new Date(), 4).toISOString(),
    strategy: 'Supply/Demand',
    notes: 'Rejected at daily resistance.',
    emotionalState: 'Neutral',
    confidence: 7,
    newsImpact: 'Yellow',
    followedRules: ['Liquidity Sweep'],
    mistakeTags: [],
    pnl: 300,
    pnlPercentage: 0.27,
    riskReward: 1.5,
    targetRR: 2.0,
    exitStatus: 'Closed Manually',
  },
  {
    id: '3',
    asset: 'NVDA',
    marketType: 'Stocks',
    entryPrice: 850,
    exitPrice: 830,
    positionSize: 10,
    side: 'Long',
    entryDate: subDays(new Date(), 3).toISOString(),
    exitDate: subDays(new Date(), 3).toISOString(),
    strategy: 'Breakout',
    notes: 'Poor entry, should have waited for retest.',
    emotionalState: 'Anxious',
    confidence: 5,
    newsImpact: 'Red',
    followedRules: [],
    mistakeTags: ['FOMO'],
    pnl: -200,
    pnlPercentage: -2.35,
    riskReward: -1.0,
    targetRR: 2.5,
    exitStatus: 'Closed by S/L',
  },
  {
    id: '4',
    asset: 'Gold',
    marketType: 'Futures',
    entryPrice: 2350,
    exitPrice: 2380,
    positionSize: 5,
    side: 'Long',
    entryDate: subDays(new Date(), 2).toISOString(),
    exitDate: subDays(new Date(), 2).toISOString(),
    strategy: 'Scalping',
    notes: 'Quick momentum play.',
    emotionalState: 'Excited',
    confidence: 9,
    newsImpact: 'None',
    followedRules: ['Structure Break'],
    mistakeTags: [],
    pnl: 1500,
    pnlPercentage: 1.27,
    riskReward: 3.2,
    targetRR: 4.0,
    exitStatus: 'Closed by T/P',
  },
  {
    id: '5',
    asset: 'ETH/USDT',
    marketType: 'Crypto',
    entryPrice: 3500,
    exitPrice: 3450,
    positionSize: 2,
    side: 'Long',
    entryDate: subDays(new Date(), 1).toISOString(),
    exitDate: subDays(new Date(), 1).toISOString(),
    strategy: 'Mean Reversion',
    notes: 'Stops hit, market too volatile.',
    emotionalState: 'Greedy',
    confidence: 4,
    newsImpact: 'Orange',
    followedRules: [],
    mistakeTags: ['Overtrading'],
    pnl: -100,
    pnlPercentage: -1.4,
    riskReward: -0.5,
    targetRR: 2.0,
    exitStatus: 'Closed by S/L',
  }
];
